on: 
  workflow_dispatch:
  push:

jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
    - name: Install ZeroTier Client
      run: |
        curl -s https://install.zerotier.com | sudo bash
    - name: Join ZeroTier Network
      run: |
        sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORKID }}
    - name: Authorize ZeroTier Client
      shell: bash
      run: |
        result=$(sudo zerotier-cli info)
        clientId=$(echo $result | grep -oE '[A-Za-z0-9]{10}')
        body='{ "config": { "authorized": true }}'
        uri="https://api.zerotier.com/api/v1/network/${{ secrets.ZEROTIER_NEWORKID }}/member/${ClientId}"      
        curl -v -X POST -H "Content-Type: application/json" -H "Authorization: key ${{ secrets.ZEROTIER_APIKEY }}" -d '${body}' $uri



      
