on: 
  workflow_dispatch:
  push:

jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
    - name: Install ZeroTier Client
      run: |
        curl -s https://install.zerotier.com | sudo bash
    - name: Join ZeroTier Network
      run: |
        sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORKID }}
    - name: Authorize ZeroTier Client
      shell: bash
      env: 
        ZEROTIER_APIKEY: ${{ secrets.ZEROTIER_APIKEY }}
        ZEROTIER_NEWORKID: ${{ secrets.ZEROTIER_NEWORKID }}
      run: |
        result=$(sudo zerotier-cli info)
        clientId=$(echo $result | grep -oE '[A-Za-z0-9]{10}')
        body='{ "config": { "authorized": true }}'
        uri="https://api.zerotier.com/api/v1/network/$ZEROTIER_NEWORKID/member/$clientId"      
        curl -v -X POST -H "Content-Type: application/json" -H "Authorization: token $ZEROTIER_APIKEY" -d '{ "config": { "authorized": true }}' $uri
    - name: Test Connectivity to ZeroTier Router
      run: |
        ping -c 10 192.168.194.114
    - name: Test Connectivity to ZeroTier Router private IPv4 address
      run: |
        ping -c 10 10.98.10.121


      
